
server:
  servlet:
    context-path: /api
  port: 8087
#chatgpt大语言模型
openai:
  chatGpt:
    model: gpt-3.5-turbo
    api:
      key: sk-YbqEArlx28pD1ebgVbGi7VxvLAQAbhNq1KtiFjSgkJLOXPmQ # 必备的token
      url: https://api.chatanywhere.tech/v1/chat/completions # 请求地址
    max-completions: 1 # 聊天数量
    temperature: 1 # 参数
    max-tokens: 10000 # 聊天完成时生成的最大令牌数